version: '3.8'
services:
  php70:
    build: ./php70
    ports:
      - "9004:9000"
    volumes:
      - ~/work:/www/project
      - ./deps/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./deps/supervisor.d:/etc/supervisor/supervisor.d:ro
      - ./hosts:/www/hosts:ro
      - ./logs/70:/usr/local/var/log
      - ./logs/70:/data/log/service
      - ./logs/70:/var/log/lazy
      - ~/worklogs/log:/data/log
      - ~/dockers-config/rainbow-niffler:/rainbow-niffler
      - ~/dockers-config/niffler:/niffler
      - ./conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - wpt-network

  php72:
    build: ./php72
    ports:
      - "9006:9000"
      - "9010:9009"
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./deps/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./deps/supervisor.d:/etc/supervisor/supervisor.d:ro
      - ~/work:/www/project
      - ./logs/72:/usr/local/var/log
      - ./logs/72:/data/log/service
      - ./logs/72:/var/log/lazy
      - ~/worklogs/log:/data/log
      - ~/dockers-config/rainbow-niffler:/rainbow-niffler
      - ~/dockers-config/niffler:/niffler
    networks:
      - wpt-network

  php74:
    build: ./php74
    ports:
      - "9007:9000"
      - "9011:9009"
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./deps/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./deps/supervisor.d:/etc/supervisor/supervisor.d:ro
      - ~/work:/www/project
      - ./logs/74:/usr/local/var/log
      - ./logs/74:/data/log/service
      - ./logs/74:/var/log/lazy
      - ~/worklogs/log:/data/log
      - ~/dockers-config/rainbow-niffler:/rainbow-niffler
      - ~/dockers-config/niffler:/niffler
      - ./conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - wpt-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "php70"
      - "php72"
      - "php74"
    volumes:
      - ~/worklogs/log:/data/log
      - ~/work:/www/project
      - ./nginx/sites:/etc/nginx/http.d
    networks:
      - wpt-network

  mysql:
    build: ./mysql
    ports:
      - "33060:3306"
    volumes:
      - ./mysql/mysql:/var/lib/mysql:rw
      - ./mysql/logs:/var/lib/mysql-logs:rw
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 5eNyj6Nf # root密码 自行修改
      MYSQL_USER: test # 子账号
      MYSQL_PASSWORD: 2589632147 # 子密码
    command: "--character-set-server=utf8mb4"
    networks:
      - wpt-network

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs/redis.log:/data/redis.log
    #cpu和内存的默认限制 不开启
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 500M
    networks:
      - wpt-network

  elasticsearch:
    #build是做构建镜像使用的，使用了image直接up -d即可
    image: elasticsearch:7.17.0
    environment:
      - "cluster.name=jaeger" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" #设置使用jvm内存大小
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - cluster.name=jaeger-cluster
      - "xpack.security.enabled=false"
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - wpt-network

  # 本机电脑无法支撑屏蔽该容器正常使用机器内存需要满足大于等于16G
  # kibana:
  #   image: kibana:7.17.0
  #   links:
  #     - elasticsearch:localhost #可以用localhost这个域名访问elasticsearch服务
  #   depends_on:
  #     - elasticsearch #kibana在elasticsearch启动之后再启动
  #   environment:
  #     - "elasticsearch.hosts=http://localhost:9200" #设置访问elasticsearch的地址
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - wpt-network

  # logstash:
  #   image: logstash:7.17.0
  #   volumes:
  #     - ./logstash/conf:/usr/share/logstash/pipeline/ #挂载logstash的配置文件
  #   depends_on:
  #     - elasticsearch #kibana在elasticsearch启动之后再启动
  #   links:
  #     - elasticsearch:localhost #可以用localhost这个域名访问elasticsearch服务
  #   ports:
  #     - "4560:4560"
  #   networks:
  #     - wpt-network

  jaeger:
    build: ./jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "5775:5775/udp"
    volumes:
      - ./jaeger/tmp:/tmp
    depends_on:
      - elasticsearch
    networks:
      - wpt-network

networks:
  wpt-network:
    driver: bridge
    ipam:
      driver: default
