version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd --broadcast-address=47.108.249.58
    ports:
      - "4160:4160"
      - "4161:4161"

  nsq-auth:
    image: zhimiao/nsq-auth:latest
    restart: always
    command: --secret="ASDt256*@1ghOPTs"

  nsqd-01:
    image: nsqio/nsq
    command: /nsqd  --lookupd-tcp-address=47.108.249.58:4160 --broadcast-address=47.108.249.58 --auth-http-address="nsq-auth:1325"
    depends_on:
      - nsqlookupd
      - nsq-auth
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqd-02:
    image: nsqio/nsq
    command: /nsqd  --lookupd-tcp-address=47.108.249.58:4160 --broadcast-address=47.108.249.58 --tcp-address=0.0.0.0:4152 --http-address=0.0.0.0:4153 --auth-http-address="nsq-auth:1325"
    depends_on:
      - nsqlookupd
      - nsq-auth
    ports:
      - "4152:4152"
      - "4153:4153"

  nsqd-03:
    image: nsqio/nsq
    command: /nsqd  --lookupd-tcp-address=47.108.249.58:4160 --broadcast-address=47.108.249.58 --tcp-address=0.0.0.0:4154 --http-address=0.0.0.0:4155 --auth-http-address="nsq-auth:1325"
    depends_on:
      - nsqlookupd
      - nsq-auth
    ports:
      - "4154:4154"
      - "4155:4155"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=47.108.249.58:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"